application: hyphalpha
version: 1
runtime: python27
api_version: 1
threadsafe: true

builtins:
- django_wsgi: on

handlers:
- url: /css
  static_dir: assets/css

- url: /js
  static_dir: assets/js

- url: /_ah/spi/.*
  script: services.api.server

- url: /.*
  script: urls.app


libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
- name: pycrypto
  version: latest
- name: endpoints
  version: 1.0